table: 
    author: 
        title: 
            fr: Auteur
        field: 
            id: 
                type: id
                primary: true
            firstname: 
                type: string
                is_title: true
            lastname: 
                type: string
                is_title: true
        allowed_items: none
    multimedia: 
        title: 
            fr: Elément multimédia
        help: 
            fr: >
                Unélément multimédia peut être un film, un son, une musique, etc... Attachez un fichier à cet
                élément pour qu'il soit disponible en téléchargement
        icon: video-x-generic.png
        title_field: title
        field: 
            id: 
                type: id
            title: 
                title: 
                    fr: Titre
                help: 
                    fr: Un titre court est plus percutant
                type: string
                is_title: true
            intro: 
                title: 
                    fr: Introduction
                help: 
                    fr: Introduction courte
                type: text
            body: 
                title: 
                    fr: Corps du texte
                help: 
                    fr: Regardez dans l'aide pour ajouter des images
                type: richtext
            cover: 
                title: 
                    fr: Vignette
                type: file
