table:
    publication: 
        title: 
            fr: Publication
        icon: book.png
        title_field: title
        field: 
            id: 
                type: id
            title: 
                title: 
                    fr: Titre
                help: 
                    fr: Un titre court est plus percutant
                type: string
                is_title: true
            intro: 
                title: 
                    fr: Introduction
                help: 
                    fr: Introduction courteà la publication
                type: richtext
            authors: 
                title: 
                    fr: Auteurs
                type: text
            body: 
                title: 
                    fr: Corps du texte
                help: 
                    fr: Texte plus long (si nécessaire)
                type: richtext
            cover: 
                title: 
                    fr: Couverture
                type: file
            pdf: 
                title: 
                    fr: Fichier pdf
                type: file
            publication: 
                title: 
                    fr: Date de publication
                help: 
                    fr: Il faut pour le moment mettre aaaa-mm-jj (année, mois, jour)
                type: date
