table:    
    relation: 
        title_field: title
        field: 
            id: 
                type: id
                primary: false
            source_class: 
                type: string
                primary: true
                use: 
                    list: true
            source_type: 
                type: string
                primary: true
                use: 
                    list: true
            source_id: 
                type: text
                primary: true
                use: 
                    list: true
            target_class: 
                type: string
                primary: true
                use: 
                    list: true
            target_type: 
                type: string
                primary: true
                use: 
                    list: true
            target_id: 
                type: text
                primary: true
                use: 
                    list: true
            sort_order: 
                type: order
                use: 
                    list: true
