table:
    user: 
        title: 
            fr: Utilisateurs
        help: 
            fr: Liste des personnes pouvant utiliser le site et modifier son contenu
        field: 
            id: 
                type: id
                primary: true
            login: 
                is_title: true
                type: login
            password: 
                type: password
